## GarudaRice fish defaults (adapted from Garuda Linux garuda-fish-config)
# Do not edit this file in-place if installed system-wide; customize ~/.config/fish/config.fish instead.

set fish_greeting
set VIRTUAL_ENV_DISABLE_PROMPT "1"
set -x SHELL (command -v fish)

# Use bat for man pages when available
if type -q bat
  set -xU MANPAGER "sh -c 'col -bx | bat -l man -p'"
  set -xU MANROFFOPT "-c"
end

# done plugin hints (optional)
set -U __done_min_cmd_duration 10000
set -U __done_notification_urgency_level low

if test -f ~/.fish_profile
  source ~/.fish_profile
end

if test -d ~/.local/bin
  if not contains -- ~/.local/bin $PATH
    set -p PATH ~/.local/bin
  end
end

## Starship prompt
if status --is-interactive; and type -q starship
  source (starship init fish --print-full-init | psub)
end

## !! and !$ helpers
function __history_previous_command
  switch (commandline -t)
  case "!"
    commandline -t $history[1]; commandline -f repaint
  case "*"
    commandline -i !
  end
end

function __history_previous_command_arguments
  switch (commandline -t)
  case "!"
    commandline -t ""
    commandline -f history-token-search-backward
  case "*"
    commandline -i '$'
  end
end

if test "$fish_key_bindings" = fish_vi_key_bindings
  bind -Minsert ! __history_previous_command
  bind -Minsert '$' __history_previous_command_arguments
else
  bind ! __history_previous_command
  bind '$' __history_previous_command_arguments
end

function history
  builtin history --show-time='%F %T '
end

function backup --argument filename
  cp $filename $filename.bak
end

function copy
  set count (count $argv | tr -d \n)
  if test "$count" = 2; and test -d "$argv[1]"
    set from (echo $argv[1] | string trim --right --chars=/)
    set to (echo $argv[2])
    command cp -r $from $to
  else
    command cp $argv
  end
end

function __garuda_rice_fastfetch
  if status --is-interactive; and type -q fastfetch
    set -l preset
    for p in \
        /usr/local/share/fastfetch/presets/dr460nized.jsonc \
        /usr/share/fastfetch/presets/dr460nized.jsonc \
        $HOME/.local/share/fastfetch/presets/dr460nized.jsonc
      if test -f $p
        set preset $p
        break
      end
    end
    if test -n "$preset"
      fastfetch --config $preset
    else
      fastfetch
    end
  end
end

function gitg
  git gui
end

## Useful aliases
if type -q eza
  alias ls 'eza -al --group-directories-first'
  alias lsz 'eza -al --total-size --group-directories-first'
  alias la 'eza -a --group-directories-first'
  alias ll 'eza -l --group-directories-first'
  alias lt 'eza -aT --group-directories-first'
  alias l. 'eza -ald --group-directories-first .*'
end

if type -q bat
  alias cat 'bat --style header,snip,changes'
end

alias .. 'cd ..'
alias ... 'cd ../..'
alias .... 'cd ../../..'
alias ..... 'cd ../../../..'
alias ...... 'cd ../../../../..'
alias dir 'dir --color=auto'
alias vdir 'vdir --color=auto'
if type -q ugrep
  alias grep 'ugrep --color=auto'
  alias egrep 'ugrep -E --color=auto'
  alias fgrep 'ugrep -F --color=auto'
else
  alias grep 'grep --color=auto'
  alias egrep 'egrep --color=auto'
  alias fgrep 'fgrep --color=auto'
end
alias ip 'ip -color'
alias psmem 'ps auxf | sort -nr -k 4'
alias psmem10 'ps auxf | sort -nr -k 4 | head -10'
alias tarnow 'tar -acf '
alias untar 'tar -zxvf '
alias wget 'wget -c '
alias please 'sudo'
alias tb 'nc termbin.com 9999'
alias jctl 'journalctl -p 3 -xb'
alias helpme 'echo "To print basic information about a command use tldr <command>"'

# Distro-specific aliases
set -l _rice_root
for d in /usr/local/share/garuda-rice /usr/share/garuda-rice $HOME/.local/share/garuda-rice
  if test -d $d/distro
    set _rice_root $d
    break
  end
end
if test -n "$_rice_root"
  set -l fam (cat $_rice_root/distro/current 2>/dev/null)
  if test -z "$fam"
    set fam arch
  end
  # fish cannot source bash .inc — map via a small fish include if present, else skip
  # We emit fish-compatible distro files as .fish
  if test -f $_rice_root/distro/$fam.fish
    source $_rice_root/distro/$fam.fish
  end
end
